/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '854190' at '16-3-29 上午10:47' with Gradle 2.12
 *
 * @author 854190, @date 16-3-29 上午10:47
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
